package com.example.shopper;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.View;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.ListView;

public class MainActivity extends AppCompatActivity {

    // declare an Intent
    Intent intent;

    // declare a database handler
    DBHandler dbHandler;

    // declare a Shopping Lists Cursor Adapter
    ShoppingLists shoppingListsAdapter;

    // declare a ListView
    ListView shopperListView;

    /**
     * This method initializes the Action Bar and View of
     * the Main Activity.
     * @param savedInstanceState
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // this code generated by Android Studio initializes the
        // View and Action Bar of the Main Activity
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        // initialize the database handler
        dbHandler = new DBHandler(this, null);

        // initialize the ListView
        shopperListView = (ListView) findViewById(R.id.shopperListView);

        // initialize the Shopping Lists Cursor Adapter
        shoppingListsAdapter = new ShoppingLists(this, dbHandler.getShoppingLists(), 0);

        // set Shopping Lists Cursor Adapter on ListView
        shopperListView.setAdapter(shoppingListsAdapter);
    }

    /**
     * This method further initializes the Action Bar of
     * the Main Activity.  It gets the code we wrote in the
     * menu main and incorporates it into the Action Bar.
     * @param menu
     * @return
     */
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    /**
     * This method gets called when an item in the overflow menu is selected and
     * it controls what happens when the item is selected.
     * @param item item selected in the overflow menu.  It contains information
     *             about the item; for example, its id.
     * @return true if an item was selected; else returns false
     */
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {

        // get the id of the item that was selected
        switch (item.getItemId()){
            case R.id.action_home :
                // initializing an Intent for the Main Activity, starting it
                // and returning true
                intent = new Intent(this, MainActivity.class);
                startActivity(intent);
                return true;
            case R.id.action_create_list :
                // initializing an Intent for the Create List Activity, starting it
                // and returning true
                intent = new Intent(this, CreateList.class);
                startActivity(intent);
                return true;
                default:
                    return super.onOptionsItemSelected(item);
        }
    }

    public void openCreateList(View view) {
        // initializing an Intent for the Create List Activity and starting it
        intent = new Intent(this, CreateList.class);
        startActivity(intent);
    }
}
